- hosts: all
  gather_facts: no
  remote_user: '{{ ansible_user }}'
  become: yes
  become_user: '{{ ansible_user }}'
  vars_files:
    - secrets.yml
    - config.yml

  tasks:    
    - name: install common dependencies
      include_tasks: tasks/install-common-dependencies.yml
    
    - name: configure server nodes
      include_tasks: tasks/configure-server-nodes.yml
      when: inventory_hostname in groups['server_nodes']

    - name: configure client nodes
      include_tasks: tasks/configure-client-nodes.yml
      when: inventory_hostname in groups['client_nodes']

    - name: run fabio lb
      include_tasks: tasks/run-fabio-job.yml
      when: inventory_hostname == 'server-01'
    
    - name: install and run jenkins
      include_tasks: tasks/run-jenkins.yml
      when: inventory_hostname == 'server-01'