- hosts: all
  remote_user: '{{ ansible_user }}'
  become: yes
  become_user: '{{ ansible_user }}'
  vars_files:
    - vault.yml

  tasks:    
    - name: install common dependencies
      vars:
        consul_version: 1.8.4
        nomad_version: 0.12.5
      include_tasks: tasks/install-common-dependencies.yml
    
    - name: configure server agents
      include_tasks: tasks/configure-server-agents.yml
      when: inventory_hostname in groups['server_nodes']

    - name: configure client agents
      include_tasks: tasks/configure-client-agents.yml
      when: inventory_hostname in groups['client_nodes']