- hosts: all
  gather_facts: no
  remote_user: '{{ ansible_user }}'
  become: yes
  become_user: '{{ ansible_user }}'
  vars_files:
    - vault.yml

  tasks:    
    - name: install common dependencies
      vars:
        consul_version: 1.9.3
        nomad_version: 1.0.3
      include_tasks: tasks/install-common-dependencies.yml
    
    - name: configure server agents
      include_tasks: tasks/configure-server-agents.yml
      when: inventory_hostname in groups['server_nodes']

    - name: configure client agents
      include_tasks: tasks/configure-client-agents.yml
      when: inventory_hostname in groups['client_nodes']

    - name: run nomad jobs
      include_tasks: tasks/run-nomad-jobs.yml
      when: inventory_hostname == 'server-01'

    #- name: run jenkins
    #  include_tasks: tasks/run-jenkins.yml
    #  when: inventory_hostname == 'server-01'