- hosts: all
  gather_facts: no
  remote_user: '{{ ansible_user }}'
  become: yes
  become_user: '{{ ansible_user }}'
  vars_files:
    - secrets.yml
    - config.yml

  tasks:    
    - name: configure common dependencies
      include_tasks: tasks/configure-common-dependencies.yml
    
    - name: configure server agents
      include_tasks: tasks/configure-server-agents.yml
      when: inventory_hostname in groups['server_nodes']

    - name: configure client agents
      include_tasks: tasks/configure-client-agents.yml
      when: inventory_hostname in groups['client_nodes']

    - name: run fabio
      include_tasks: tasks/run-fabio.yml
      when: inventory_hostname == 'server-01'

    - name: run jenkins
      include_tasks: tasks/run-jenkins.yml
      when: inventory_hostname == 'server-01'