- name: install tls consul server certificate
  copy:
    content: '{{ consul_server_cert }}'
    dest: /etc/consul.d/consul-cert.pem
    owner: root
    group: root
    mode: 0644

- name: install tls consul server key
  copy:
    content: '{{ consul_server_key }}'
    dest: /etc/consul.d/consul-key.pem
    owner: root
    group: root
    mode: 0600  

- name: copy consul-server-config.hcl file
  template:
    src: ./templates/consul-server-config.hcl.j2
    dest: /etc/consul.d/server.hcl
    owner: consul
    group: consul
    mode: 640

- name: copy nomad-server-config.hcl file
  template:
    src: ./templates/nomad-server-config.hcl.j2
    dest: /etc/nomad.d/nomad.hcl

- name: copy fabio.hcl file
  template:
    src: ./templates/fabio.hcl.j2
    dest: /etc/nomad.d/fabio.hcl

- name: copy jenkins.service file
  template:
    src: ./templates/jenkins.service.j2
    dest: /usr/lib/systemd/system/jenkins.service
    owner: root
    group: root
    mode: 640

- name: run server agents
  include_tasks: tasks/run-cluster-agents.yml

- name: start jenkins service
  systemd:
    name: jenkins
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: run fabio job
  command: nomad job run /etc/nomad.d/fabio.hcl