- name: install common packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - software-properties-common
    - gnupg-agent
    - unzip

- name: download consul
  get_url:
    url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /tmp

- name: extract consul
  unarchive:
    src: /tmp/consul_{{ consul_version }}_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes

- name: set consul owner
  file:
    path: /usr/bin/consul
    owner: root
    group: root

- name: autocomplete consul installation
  command: consul -autocomplete-install && complete -C /usr/bin/consul consul
  ignore_errors: yes

- name: create consul group
  group:
    name: consul

- name: create consul user
  user:
    name: consul
    group: consul
    home: /etc/consul.d
    shell: /bin/false

- name: create /opt/consul directory
  file:
    path: /opt/consul
    state: directory

- name: set /opt/consul owner
  file:
    path: /opt/consul
    owner: consul
    group: consul

- name: install consul tls ca
  copy:
    content: "{{ consul_ca }}"
    dest: /etc/consul.d/consul-ca.pem
    owner: root
    group: root
    mode: 644

- name: install consul tls ca key
  copy:
    content: "{{ consul_ca_key }}"
    dest: /etc/consul.d/consul-ca-key.pem
    owner: root
    group: root
    mode: 644

- name: copy consul.hcl file
  template:
    src: ./templates/consul-config.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul  
    mode: 644

- name: copy consul.service file
  template:
    src: ./templates/consul.service.j2
    dest: /usr/lib/systemd/system/consul.service
    owner: root
    group: root
    mode: 644

- name: download nomad
  get_url:
    url: https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip
    dest: /tmp

- name: extract nomad
  unarchive:
    src: /tmp/nomad_{{ nomad_version }}_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes

- name: set nomad owner
  file:
    path: /usr/bin/nomad
    owner: root
    group: root

- name: autocomplete nomad installation
  command: nomad -autocomplete-install && complete -C /usr/local/bin/nomad nomad
  ignore_errors: yes

- name: create /opt/nomad directory
  file:
    path: /opt/nomad
    state: directory

- name: create nomad config folder
  file:
    path: /etc/nomad.d
    state: directory

- name: copy nomad.hcl file
  template:
    src: ./templates/nomad-config.hcl.j2
    dest: /etc/nomad.d/nomad.hcl

- name: copy nomad.service file
  template:
    src: ./templates/nomad.service.j2
    dest: /usr/lib/systemd/system/nomad.service
    owner: root
    group: root
    mode: 644

- name: add an apt sign key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: install docker packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: add user to docker group
  user:
    name: root
    group: docker
