- name: start consul service
  systemd:
    name: consul
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: start nomad service
  systemd:
    name: nomad
    state: restarted
    enabled: yes
    daemon_reload: yes